### ISSUE TITLE
[Bug] Notebooks/Screens not shown in Slithin

### ISSUE THREAD

**Issue by sil-van** [furesoft/Slithin#154]
**Describe the bug**
After initial connect, it shows a small warning, but the Screens (Sart, power off, etc.) are blank.
Also the Notebook/Template Tab are both empty.

Metadata seems to be synced (version, email) however

**To Reproduce**
1. Install Slithin
2. Connect Tablet

**Expected behavior**
I guess show my Notebooks that are on the remarkable?

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version Slithin: 1.0.14.0
 - Version reMarkable: 2.12.3.606

**Additional context** 
Logfile:
```
2022-04-28 17:19:37.341 +02:00 [INF] Downloading 'xochitl.conf'
2022-04-28 17:19:37.431 +02:00 [INF] Initialize Screens
2022-04-28 17:19:37.436 +02:00 [INF] Loading Internal Tools
2022-04-28 17:19:37.481 +02:00 [ERR] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at Slithin.Core.Services.Implementations.LoadingServiceImpl.LoadTemplates() in /home/runner/work/Slithin/Slithin/Source/Slithin/Core/Services/Implementations/LoadingServiceImpl.cs:line 59
   at Slithin.ViewModels.Pages.DevicePageViewModel.<OnLoad>b__32_0() in /home/runner/work/Slithin/Slithin/Source/Slithin/ViewModels/Pages/DevicePageViewModel.cs:line 99
   at Slithin.MessageHandlers.PostActionMessageHandler.HandleMessage(PostActionMessage message) in /home/runner/work/Slithin/Slithin/Source/Slithin/MessageHandlers/PostActionMessageHandler.cs:line 10
   at Slithin.Core.Messaging.MessageRouter.<>c__DisplayClass2_0`1.<Register>b__0(Object _) in /home/runner/work/Slithin/Slithin/Source/Slithin/Core/Messaging/MessageRouter.cs:line 26
   at Slithin.Core.Messaging.MessageRouter.Route(Object msg) in /home/runner/work/Slithin/Slithin/Source/Slithin/Core/Messaging/MessageRouter.cs:line 36
   at Slithin.Core.Services.Implementations.MailboxServiceImpl.<Init>b__6_0(MailboxProcessor`1 _) in /home/runner/work/Slithin/Slithin/Source/Slithin/Core/Services/Implementations/MailboxServiceImpl.cs:line 38
   at Actress.MailboxProcessor`1.<Start>g__StartAsync|14_0()
2022-04-28 17:19:37.481 +02:00 [INF] An Error occured. See (/home/silvan/.../log.txt)
```

**Comment by furesoft** [comment]
Have already tried Slithin before? If yes try deleting the Slithin directory in your documents and try again

**Comment by jw5801** [comment]
Seeing the same issue here, with the same error in the log. Slithin installed from the Windows store (not sure how to tell which version I have from either the Windows store or within the app).

I've never used Slithin before (trying it for the first time today). I've tried deleting the user directory and starting again with no change.

**Comment by furesoft** [comment]
The next update will fix the problem. I will publish it today

**Comment by furesoft** [comment]
Did you test the new version?

**Comment by furesoft** [comment]
You're welcome
