### ISSUE TITLE
[Bug]cannot synchronize the notebook(RM2)

### ISSUE THREAD

**Issue by sxtiger** [furesoft/Slithin#256]
**Describe the bug**
windows 11 , get the slithin from MicrosoftStore, connect the rm2 via usb, then open the app, but cannot synchronize the notebook.

**Additional context** 
THE LOG.TXT :
2022-10-11 15:54:00.766 +08:00 [ERR] Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Boolean'. Path 'modified', line 5, position 20.
 ---> System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Slithin.Core.Remarkable.Models.Metadata.Load(String id)
   at Slithin.Core.Services.Implementations.LoadingServiceImpl.LoadNotebooks()
   at Slithin.ViewModels.Pages.DevicePageViewModel.<OnLoad>b__32_1()
   at Slithin.MessageHandlers.PostActionMessageHandler.HandleMessage(PostActionMessage message)
   at Slithin.Core.Messaging.MessageRouter.<>c__DisplayClass2_0`1.<Register>b__0(Object _)
   at Slithin.Core.Messaging.MessageRouter.Route(Object msg)
   at Slithin.Core.Services.Implementations.MailboxServiceImpl.<Init>b__6_0(MailboxProcessor`1 _)
   at Actress.MailboxProcessor`1.<Start>g__StartAsync|14_0()
2022-10-11 15:54:00.767 +08:00 [INF] An Error occured. See (\\...Documents\Slithin\log.txt)

**Comment by furesoft** [comment]
Thanks for your report. I will fix it and publish an update as soon as possible

**Comment by sxtiger** [comment]
rm2 version: 2.15.0.1067
