### ISSUE TITLE
[Bug] Application error while connecting to device

### ISSUE THREAD

**Issue by tbrandysky** [furesoft/Slithin#81]
**Describe the bug**
I'm getting constant errors while trying to connect to my Remarkable 2.
The application can not even be closed and I need to kill the process.

**To Reproduce**
1. Start the app
2. Enter IP and ssh password to connect to my device
3. I get an error

**Screenshots**
![Screenshot from 2022-02-18 12-31-23](https://user-images.githubusercontent.com/3275770/154688836-2702ecef-4636-4c51-aaed-223d95835b61.png)

Content of log file:

$ tail -f log.txt 
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at Slithin.Core.Migration.MoveFile(String dir, String newDir, String file) in D:\a\Slithin\Slithin\Source\Slithin\Core\Migration.cs:line 82
   at Slithin.Core.Migration.MigrateToNewFolderStructure() in D:\a\Slithin\Slithin\Source\Slithin\Core\Migration.cs:line 49
   at Slithin.Core.Migration.<StartMigration>b__9_0() in D:\a\Slithin\Slithin\Source\Slithin\Core\Migration.cs:line 36
   at Slithin.Core.MessageHandlers.PostActionMessageHandler.HandleMessage(PostActionMessage message) in D:\a\Slithin\Slithin\Source\Slithin\Core\MessageHandlers\PostActionMessageHandler.cs:line 9
   at Slithin.Core.MessageRouter.<>c__DisplayClass2_0`1.<Register>b__0(Object _) in D:\a\Slithin\Slithin\Source\Slithin\Core\MessageRouter.cs:line 24
   at Slithin.Core.MessageRouter.Route(Object msg) in D:\a\Slithin\Slithin\Source\Slithin\Core\MessageRouter.cs:line 34
   at Slithin.Core.Services.Implementations.MailboxServiceImpl.<Init>b__4_0(MailboxProcessor`1 _) in D:\a\Slithin\Slithin\Source\Slithin\Core\Services\Implementations\MailboxServiceImpl.cs:line 28
   at Actress.MailboxProcessor`1.<Start>g__StartAsync|14_0()
2022-02-18 14:06:06.846 +01:00 [INF] An Error occured. See log file
2022-02-18 14:07:31.526 +01:00 [INF] Initialize Screens
2022-02-18 14:07:31.537 +01:00 [INF] Loading Internal Tools
2022-02-18 14:07:31.827 +01:00 [INF] Downloading Screens
2022-02-18 14:07:33.067 +01:00 [INF] Downloading Templates
2022-02-18 14:07:47.248 +01:00 [INF] Downloading Notebooks
2022-02-18 14:07:47.306 +01:00 [INF] Downloading 0b03acdc-7c71-4598-9984-105268a5f80b.content 0 Bytes/ 4 Bytes
2022-02-18 14:07:47.307 +01:00 [INF] Downloading 0b03acdc-7c71-4598-9984-105268a5f80b.content 4 Bytes/ 4 Bytes
2022-02-18 14:07:47.403 +01:00 [ERR] System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory
   at DesktopBridge.Helpers.GetCurrentPackageFullName(Int32& packageFullNameLength, StringBuilder packageFullName)
   at DesktopBridge.Helpers.IsRunningAsUwp()
   at Slithin.Core.MessageHandlers.CheckForUpdatesMessageHandler.HandleMessage(CheckForUpdateMessage message) in D:\a\Slithin\Slithin\Source\Slithin\Core\MessageHandlers\CheckForUpdatesMessageHandler.cs:line 10
   at Slithin.Core.MessageRouter.<>c__DisplayClass2_0`1.<Register>b__0(Object _) in D:\a\Slithin\Slithin\Source\Slithin\Core\MessageRouter.cs:line 24
   at Slithin.Core.MessageRouter.Route(Object msg) in D:\a\Slithin\Slithin\Source\Slithin\Core\MessageRouter.cs:line 34
   at Slithin.Core.Services.Implementations.MailboxServiceImpl.<Init>b__4_0(MailboxProcessor`1 _) in D:\a\Slithin\Slithin\Source\Slithin\Core\Services\Implementations\MailboxServiceImpl.cs:line 28
   at Actress.MailboxProcessor`1.<Start>g__StartAsync|14_0()
2022-02-18 14:07:47.403 +01:00 [INF] An Error occured. See log file

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3 Cinnamon

**Comment by furesoft** [comment]
Problem is fixed but I have no Internet to publish newer releases/updates
